#!/usr/bin/env python3
"""Compare fractal theory predictions with simulation results.

- Loads Parquet files generated by `run_hierarchical_experiment.py`
  for each network design (nearest, dendritic, hierarchical, mst).
- Reads a simple scaling parameter set (placeholder values) that would
  normally come from GBIF trait data or literature.
- Computes the theoretical persistence using the formula from the
  fractal theory notebook:
    P(D_f, sigma, m) = exp(-m * sigma**D_f) * (1 - exp(-sigma**D_f))
- Prints a side‑by‑side table of simulated mean final population vs.
  theoretical prediction.

You can extend this script by loading real scaling parameters and adding
statistical tests (e.g., RMSE) to quantify agreement.
"""
import os
import pathlib
import pandas as pd
import math

# Placeholder fractal dimensions for each design (these could be measured from the network geometry)
FRACTAL_DIM = {
    "nearest": 1.2,
    "dendritic": 1.4,
    "hierarchical": 1.6,
    "mst": 1.1,
}

# Placeholder dispersal sigma and mortality m (same across designs for this example)
SIGMA = 0.07  # dispersal kernel scale (km)
MORTALITY = 0.3  # road mortality proportion

def theoretical_persistence(D_f, sigma=SIGMA, m=MORTALITY):
    return math.exp(-m * (sigma ** D_f)) * (1 - math.exp(-(sigma ** D_f)))

def load_simulated_mean(design, city="Montreal"):
    analysis_root = pathlib.Path("analysis") / f"{city}_{design}"
    parquet_path = analysis_root / "simulation_results.parquet"
    if not parquet_path.is_file():
        return None
    df = pd.read_parquet(parquet_path)
    return df["final_population"].mean()

def main():
    print("Design | Simulated Mean | Theoretical Persistence")
    print("------ | -------------- | ----------------------")
    for design, D_f in FRACTAL_DIM.items():
        sim_mean = load_simulated_mean(design)
        theory = theoretical_persistence(D_f)
        sim_str = f"{sim_mean:.2f}" if sim_mean is not None else "N/A"
        print(f"{design:6} | {sim_str:14} | {theory:.4f}")

if __name__ == "__main__":
    main()
