#!/usr/bin/env python3
"""Run a small, deterministic environmental workflow for ScienceClaw smoke tests.

The demo intentionally avoids API keys, network access, and large downloads. It
creates a synthetic habitat-suitability gradient, writes tabular outputs, draws a
simple SVG figure, and records metadata that the CMS/output review layer can
inspect.
"""

from __future__ import annotations

import argparse
import csv
import json
import math
from datetime import datetime, timezone
from pathlib import Path


def suitability(elevation: float, moisture: float, disturbance: float) -> float:
    elevation_score = math.exp(-((elevation - 1700.0) / 650.0) ** 2)
    moisture_score = 1.0 / (1.0 + math.exp(-8.0 * (moisture - 0.45)))
    disturbance_penalty = 1.0 - (0.58 * disturbance)
    return max(0.0, min(1.0, elevation_score * moisture_score * disturbance_penalty))


def build_rows() -> list[dict[str, float | int | str]]:
    rows: list[dict[str, float | int | str]] = []
    site_id = 1
    for y in range(10):
      for x in range(10):
        elevation = 900 + (x * 95) + (y * 85)
        moisture = 0.18 + (y / 13.0) + (0.08 * math.sin(x / 2.0))
        disturbance = min(1.0, max(0.0, (x / 12.0) + (0.18 * math.cos(y / 3.0))))
        score = suitability(elevation, moisture, disturbance)
        rows.append(
            {
                "site_id": site_id,
                "x": x,
                "y": y,
                "elevation_m": round(elevation, 2),
                "moisture_index": round(moisture, 3),
                "disturbance_index": round(disturbance, 3),
                "suitability": round(score, 4),
                "class": "high" if score >= 0.45 else "medium" if score >= 0.22 else "low",
            }
        )
        site_id += 1
    return rows


def write_csv(rows: list[dict[str, float | int | str]], path: Path) -> None:
    with path.open("w", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=list(rows[0].keys()))
        writer.writeheader()
        writer.writerows(rows)


def write_svg(rows: list[dict[str, float | int | str]], path: Path) -> None:
    cell = 28
    margin = 40
    width = margin * 2 + cell * 10
    height = margin * 2 + cell * 10
    colors = {
        "low": "#d7e5e2",
        "medium": "#42bcdc",
        "high": "#007135",
    }
    parts = [
        f'<svg xmlns="http://www.w3.org/2000/svg" width="{width}" height="{height}" viewBox="0 0 {width} {height}">',
        '<rect width="100%" height="100%" fill="#f7faf9"/>',
        '<text x="40" y="24" font-family="Arial, sans-serif" font-size="16" font-weight="700" fill="#234a65">Synthetic habitat suitability</text>',
    ]
    for row in rows:
        x = int(row["x"])
        y = int(row["y"])
        klass = str(row["class"])
        score = float(row["suitability"])
        opacity = 0.35 + score * 0.65
        parts.append(
            f'<rect x="{margin + x * cell}" y="{margin + (9 - y) * cell}" width="{cell - 2}" height="{cell - 2}" '
            f'rx="3" fill="{colors[klass]}" fill-opacity="{opacity:.3f}"/>'
        )
    parts.extend(
        [
            f'<text x="{margin}" y="{height - 10}" font-family="Arial, sans-serif" font-size="11" fill="#687a80">Toy data for operational validation only. No scientific claim is implied.</text>',
            "</svg>",
        ]
    )
    path.write_text("\n".join(parts) + "\n")


def write_report(rows: list[dict[str, float | int | str]], output_dir: Path) -> None:
    high = sum(1 for row in rows if row["class"] == "high")
    medium = sum(1 for row in rows if row["class"] == "medium")
    low = sum(1 for row in rows if row["class"] == "low")
    mean_score = sum(float(row["suitability"]) for row in rows) / len(rows)
    report = f"""# Demo Environmental Workflow

This report was generated by `scripts/demo_environmental_workflow.py`.

The workflow creates a synthetic 10 by 10 habitat-suitability grid from toy elevation, moisture, and disturbance gradients. It is designed to prove that the ScienceClaw appliance can run a reproducible scientific workflow, write outputs, and expose artifacts for review. It is not intended as a real ecological model.

## Outputs

- `demo_habitat_suitability.csv`
- `figures/demo_habitat_suitability.svg`
- `metadata.json`
- `report.md`

## Summary

| Class | Count |
| --- | ---: |
| High | {high} |
| Medium | {medium} |
| Low | {low} |

Mean suitability: `{mean_score:.3f}`

## Review note

Human review is still required before any result is interpreted, published, or used as evidence.
"""
    (output_dir / "report.md").write_text(report)


def main() -> int:
    parser = argparse.ArgumentParser(description="Run the ScienceClaw demo environmental workflow.")
    parser.add_argument("--workspace", default="/workspace", help="Workspace root. Defaults to /workspace.")
    parser.add_argument("--output-dir", default=None, help="Optional explicit output directory.")
    args = parser.parse_args()

    workspace = Path(args.workspace)
    output_dir = Path(args.output_dir) if args.output_dir else workspace / "outputs" / "demo"
    figures_dir = output_dir / "figures"
    output_dir.mkdir(parents=True, exist_ok=True)
    figures_dir.mkdir(parents=True, exist_ok=True)

    rows = build_rows()
    write_csv(rows, output_dir / "demo_habitat_suitability.csv")
    write_svg(rows, figures_dir / "demo_habitat_suitability.svg")
    write_report(rows, output_dir)

    metadata = {
        "workflow": "demo_environmental_workflow",
        "created_at": datetime.now(timezone.utc).isoformat(),
        "workspace": str(workspace),
        "output_dir": str(output_dir),
        "inputs": "synthetic toy gradients; no network access; no external data",
        "records": len(rows),
        "outputs": [
            "demo_habitat_suitability.csv",
            "figures/demo_habitat_suitability.svg",
            "report.md",
            "metadata.json",
        ],
        "review_status": "draft",
        "limitations": [
            "Toy operational demo only.",
            "No scientific inference should be made from these synthetic values.",
        ],
    }
    (output_dir / "metadata.json").write_text(json.dumps(metadata, indent=2) + "\n")
    print(f"ScienceClaw demo workflow wrote outputs to {output_dir}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())

